### ISSUE TITLE
Lazily compute row and column roots when repairing the square

### ISSUE THREAD

**Issue by evan-forbes** [lazyledger/rsmt2d#17]
When repairing the square, we are currently generating roots of each column and row even if there is nil data in that row or col. This is a problem because because if the underlying tree doesn't know how to handle `nil` values, then it has no choice but to panic. While there are quite a few ways to fix this, I think the fastest way would be to only compute the root of columns and rows that have no nil values. In the context of `RepairDatasquare`, this means having the ability to generate roots of single columns and rows.

This must be fixed before [#235](https://github.com/lazyledger/lazyledger-core/pull/235) and [#232](https://github.com/lazyledger/lazyledger-core/pull/232) can be completed.

**Comment by liamsi** [comment]
> While there are quite a few ways to fix this, I think the fastest way would be to only compute the root of columns and rows that have no nil values. In the context of RepairDatasquare, this means having the ability to generate roots of single columns and rows.

That sounds good to me. Do you mind drafting a minimal PR (without tests etc) to see how this would look like in code? At least it sounds like a relatively simple change.

**Comment by evan-forbes** [comment]
I cheated and wrote the code before the issue :smile: #18
