### ISSUE TITLE
RepairExtendedDataSquare hangs 

### ISSUE THREAD

**Issue by evan-forbes** [lazyledger/rsmt2d#21]
`RepairExtendedDataSquare` will hang indefinitely when attempting to recover a square with extended width of 8, and half the shares missing. If the square size or the number of missing shares are reduced, then the function returns successfully.

**Comment by liamsi** [comment]
I've briefly looked into this and I'm not sure this is an actual bug in rsmt2d 🤔 

In the case [`originalSquareWidth := 2`](https://github.com/lazyledger/lazyledger-core/blob/c0d9fa6dbc74031922852da59888e19117648c0b/p2p/ipld/read_test.go#L163
) we remove 4 of the 16 elems from data here: 
https://github.com/lazyledger/lazyledger-core/blob/c0d9fa6dbc74031922852da59888e19117648c0b/p2p/ipld/read_test.go#L210

But in the case of, e.g. `originalSquareWidth := 4` in the same place we'd delete 64 of 64 elements from `data` in the same place. So I think something else is off here.

**Comment by evan-forbes** [comment]
that's good to hear! glad it was just a test
