### ISSUE TITLE
Fix codecov reporting

### ISSUE THREAD

**Issue by liamsi** [lazyledger/rsmt2d#34]
That badge in main leads to the following page:
https://app.codecov.io/gh/lazyledger/rsmt2d
Which lists the following as recent:
![image](https://user-images.githubusercontent.com/7441766/113723359-9372ef80-96f1-11eb-8bf9-375761d490a8.png)

Also, no comments are posted from codecov to inform PR authors about coverage changes.

**Comment by liamsi** [comment]
It actually doesn't look like the action is running, too:
![image](https://user-images.githubusercontent.com/7441766/113725588-be5e4300-96f3-11eb-8d67-962f27e19097.png)

**Comment by adlerjohn** [comment]
Fixed finally with #38
