### ISSUE TITLE
Slightly misleading error message

### ISSUE THREAD

**Issue by liamsi** [lazyledger/rsmt2d#6]
https://github.com/lazyledger/rsmt2d/blob/ea94438fa457081948e455b6b6f2210458a9d699/datasquare.go#L21-L24

The error message suggests that the input length must be powers of two (2^n) while the method accepts all inputs which are square numbers (n^2). The latter makes more sense in this context.

**Comment by musalbas** [comment]
Yes, it should say "number of chunks must be _to the power_ of 2" not "_a power_ of 2".
