### ISSUE TITLE
Allow user to choose underlying Merkle tree implementation

### ISSUE THREAD

**Issue by musalbas** [lazyledger/rsmt2d#8]
See https://github.com/lazyledger/lazyledger-core/pull/83#discussion_r513560314

**Comment by liamsi** [comment]
This might imply that we need to change the API of the NMT to take in bytes instead of that `namespace.Data` interface: https://github.com/lazyledger/nmt/blob/1a5d9124ad10e40d0d743d7695e1983992089a2f/nmt.go#L236

**Comment by liamsi** [comment]
resolved in #9
